### ISSUE TITLE
Feature: add functionality for reseting to nullptr

### ISSUE THREAD

**Issue by dbkaplun** [slide-rs/atom#2]
Thanks for considering!

**Comment by torkleyy** [comment]
Hello @dbkaplun! Didn't think somebody would use this crate given that the last commit was 2015 :)

I'll look into it.

**Comment by torkleyy** [comment]
The method you're looking for is already implemented: [`Atom::take`](https://docs.rs/atom/0.3.4/atom/struct.Atom.html#method.take).

**Comment by torkleyy** [comment]
While looking through the source, I noticed there was a wrong assumption in the source which could technically cause undefined behavior.

@kvark I tried publishing `0.3.5` but I'm not an owner of this crate.

**Comment by kvark** [comment]
@torkleyy sorry about that! You've been invited now.

**Comment by torkleyy** [comment]
Thanks, fixed version is up now.
