### ISSUE TITLE
Feature: compare_and_swap/compare_exchange/compare_exchange_weak

### ISSUE THREAD

**Issue by dbkaplun** [slide-rs/atom#5]
Hello,

It would be great to have some more atomic methods available in Atom. I envision the following signatures, which attempt to maintain parity with `AtomicPtr`:

```rust
    // https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html#method.compare_and_swap
    pub fn compare_and_swap(
        &self,
        current: Option<&P>,
        new: Option<P>,
        order: Ordering,
    ) -> Result<Option<P>, (Option<P>, *mut P)>;

    // https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html#method.compare_exchange
    pub fn compare_exchange(
        &self,
        current: Option<&P>,
        new: Option<P>,
        success: Ordering,
        failure: Ordering,
    ) -> Result<Option<P>, (Option<P>, *mut P)>;

    // https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html#method.compare_exchange_weak
    pub fn compare_exchange_weak(
        &self,
        current: Option<&P>,
        new: Option<P>,
        success: Ordering,
        failure: Ordering,
    ) -> Result<Option<P>, (Option<P>, *mut P)>;
```

Would you accept a PR for this?

Thanks for considering!

**Comment by torkleyy** [comment]
Hello @dbkaplun!

@kvark and I didn't write this crate and I'm not sure how active @csherrat, the author, is. At a first thought, this seems quite hard because you cannot have the `Box` twice, but you need the pointer. Am I missing something or would this only make sense for `Arc`?

**Comment by dbkaplun** [comment]
@torkleyy,

Thanks for getting back to me. I agree that will be hard, but I think it is doable. It might only make sense for `Arc`. I haven't fleshed it out yet.

I will take a stab at it and see what I come up with. BTW I'm making some edits to the original signatures as I test the implementation.
